"""
backend/models/imagery.py
==========================
SQLAlchemy ORM models for CTHMP's three core tables:

  ImageRecord     — metadata for each ingested image
  InferenceResult — model output + provenance for each inference run
  AuditLog        — immutable append-only event log (required by ethics policy)

All timestamps are stored in UTC.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.db.base import Base


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _new_uuid() -> str:
    return str(uuid.uuid4())


# ---------------------------------------------------------------------------
# ImageRecord
# ---------------------------------------------------------------------------


class ImageRecord(Base):
    """
    Metadata for a single ingested synthetic satellite image.

    The image binary is stored in the object store (MinIO / local FS);
    this table holds only metadata and a reference path.
    """

    __tablename__ = "image_records"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_new_uuid)
    filename: Mapped[str] = mapped_column(String(255), nullable=False)
    store_path: Mapped[str] = mapped_column(String(512), nullable=False)
    sha256: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    width: Mapped[int] = mapped_column(Integer, nullable=False)
    height: Mapped[int] = mapped_column(Integer, nullable=False)
    is_synthetic: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    source_note: Mapped[str] = mapped_column(
        Text,
        default="Synthetic data generated by CTHMP synthetic_generator.py",
        nullable=False,
    )
    ingested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, nullable=False
    )
    ingested_by: Mapped[str] = mapped_column(String(128), default="system", nullable=False)

    # Relationships
    inferences: Mapped[list[InferenceResult]] = relationship(
        "InferenceResult", back_populates="image", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<ImageRecord id={self.id!r} filename={self.filename!r}>"


# ---------------------------------------------------------------------------
# InferenceResult
# ---------------------------------------------------------------------------


class InferenceResult(Base):
    """
    Stores one model inference run for an ImageRecord.

    IMPORTANT (ethics policy): verified=False until a human analyst calls
    the /verify endpoint.  No result with verified=False should be treated
    as authoritative.
    """

    __tablename__ = "inference_results"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_new_uuid)
    image_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("image_records.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Model output
    predicted_class: Mapped[int] = mapped_column(Integer, nullable=False)
    predicted_label: Mapped[str] = mapped_column(String(64), nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)

    # Raw logits stored as JSON string for explainability
    logits_json: Mapped[str] = mapped_column(Text, nullable=False, default="[]")

    # Provenance (required by ethics policy)
    model_arch: Mapped[str] = mapped_column(String(128), nullable=False)
    model_checkpoint: Mapped[str] = mapped_column(String(512), nullable=False)
    model_sha256: Mapped[str] = mapped_column(String(64), nullable=False)

    # Human verification (required before result is authoritative)
    verified: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    verified_by: Mapped[str | None] = mapped_column(String(128), nullable=True)
    verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    analyst_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    inferred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, nullable=False
    )

    # Relationships
    image: Mapped[ImageRecord] = relationship("ImageRecord", back_populates="inferences")

    def __repr__(self) -> str:
        return (
            f"<InferenceResult id={self.id!r} label={self.predicted_label!r} "
            f"verified={self.verified}>"
        )


# ---------------------------------------------------------------------------
# AuditLog
# ---------------------------------------------------------------------------


class AuditLog(Base):
    """
    Immutable append-only event log.

    Rows must never be updated or deleted (enforced at application layer).
    Each row records one of: INGEST, INFER, VERIFY, SYSTEM events.
    """

    __tablename__ = "audit_logs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    event_type: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    actor: Mapped[str] = mapped_column(String(128), nullable=False)
    resource_type: Mapped[str] = mapped_column(String(64), nullable=False)
    resource_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    detail: Mapped[str] = mapped_column(Text, nullable=False, default="{}")
    timestamp_utc: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, nullable=False, index=True
    )

    def __repr__(self) -> str:
        return (
            f"<AuditLog id={self.id} event={self.event_type!r} "
            f"resource={self.resource_id!r}>"
        )
